// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhegmniwkqxikgsnaqqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoZWdtbml3a3F4aWtnc25hcXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDU4NzgsImV4cCI6MjA3MjIyMTg3OH0.DzUZFcskWKeW7zXVEfJtkETIn3dbWsAlRDyG4QH4Wbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});